In [ ]:
Task 0

a)
Dataset : COVID-19 Dataset
Source : https://ourworldindata.org/covid-data

b)
This dataset contains global COVID-19 data collected and maintained by Our World in Data.
It includes variables such as country, date, total_cases, new_cases, total_deaths, and people_vaccinated_per_hundred
The dataset contains hundreds of thousands of rows and is continuously updated.
In this project, I plan to analyze trends in COVID-19 cases and vaccination rates over time, focusing on specific countries and comparing their development.

In [1]:
#c)
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/storage/emulated/0/Download/KakaoTalk/compact.csv")

fin = df[df["country"] == "Finland"].copy()
fin["date"] = pd.to_datetime(fin["date"])

plt.figure(figsize=(12,5))

sns.lineplot(data=fin, x="date", y="new_cases")

plt.title("Daily New COVID Cases in Finland")
plt.xlabel("Date")
plt.ylabel("New Cases")
plt.xticks(rotation=45)

plt.show()

In [2]:
df = pd.read_csv("/storage/emulated/0/Download/KakaoTalk/compact.csv")

fin = df[df["country"] == "Finland"].copy()
fin["date"] = pd.to_datetime(fin["date"])

plt.figure(figsize=(12,5))
sns.lineplot(data=fin, x="date", y="total_cases")

plt.title("Cumulative COVID Cases in Finland")
plt.xlabel("Date")
plt.ylabel("Total Cases")
plt.xticks(rotation=45)
plt.show()

In [3]:
#Task 1

from dotenv import load_dotenv
import os

load_dotenv("/storage/emulated/0/Download/.env")

api_key = os.getenv("MARKETSTACK_API_KEY")

print("KEY:", api_key)

KEY: 00cb8c5fa327ee51ebb367f06a73fa46

In [4]:
#Task 2
#a)
import requests
import pandas as pd
from dotenv import load_dotenv
import os
tickers = ["META", "AAPL", "AMZN", "NFLX", "GOOG"]
all_data = []
for ticker in tickers:
    url = "http://api.marketstack.com/v1/eod"
    params = {
    "access_key":api_key,
    "symbols":ticker,
    "date_from":"2026-03-01",
    "date_to":"2026-03-31"
    }
    response = requests.get(url, params=params)
    data = response.json()
    for item in data["data"]:
        item["ticker"] = ticker
        all_data.append(item)

#b)
df = pd.DataFrame(all_data)
display(df.head(5))

#c)
returns = {}
for ticker in tickers:
    stock = df[df["ticker"] == ticker].sort_values("date")
    start_price = stock.iloc[0]["close"]
    end_price = stock.iloc[-1]["close"]
    return_pct = (end_price - start_price) / start_price * 100
    returns[ticker] = return_pct
returns_df = pd.DataFrame(list(returns.items()), columns=["Stock", "Return%"])
display(returns_df)

#d)
best = returns_df.loc[returns_df["Return%"].idxmax()]
worst = returns_df.loc[returns_df["Return%"].idxmin()]

display("Best performer:", best)
display("Worst performer:", worst)

,open,high,low,close,volume,adj_high,adj_low,adj_close,adj_open,adj_volume,split_factor,dividend,symbol,exchange,date,ticker
0,549.98,573.69,546.77,572.13,32809500.0,573.6900,546.77,572.13,549.98,32898272.0,1.0,0.0,META,ARCX,2026-03-31T00:00:00+0000,META
1,536.38,539.55,528.54,536.38,22758800.0,539.5500,528.54,536.38,536.38,22795203.0,1.0,0.0,META,ARCX,2026-03-30T00:00:00+0000,META
2,540.10,543.60,520.26,525.72,29980300.0,543.5999,520.26,525.72,540.10,30133010.0,1.0,0.0,META,ARCX,2026-03-27T00:00:00+0000,META
3,582.49,583.00,543.35,547.54,35664700.0,583.0000,543.35,547.54,582.49,35780131.0,1.0,0.0,META,ARCX,2026-03-26T00:00:00+0000,META
4,598.74,603.62,593.40,594.89,12161179.0,603.6700,593.40,594.89,598.74,12585031.0,1.0,0.0,META,ARCX,2026-03-25T00:00:00+0000,META

  Stock    Return%
0  META -12.459453
1  AAPL  -4.128891
2  AMZN  -0.057584
3  NFLX  -0.968174
4  GOOG  -6.365061

'Best performer:'

Stock          AMZN
Return%   -0.057584
Name: 2, dtype: object

'Worst performer:'

Stock           META
Return%   -12.459453
Name: 0, dtype: object

In [5]:
#Task 3

#a)
import seaborn as sns
import matplotlib.pyplot as plt
df["date"] = pd.to_datetime(df["date"])

plt.figure(figsize=(12,6))
sns.lineplot(data=df, x="date", y="close", hue="ticker")
plt.title("FAANG Closing Prices in March 2026")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.xticks(rotation=45)
plt.legend()
plt.show()
plt.savefig("/storage/emulated/0/Download/close.png")

#b)
plt.figure(figsize=(8,5))
sns.barplot(data=returns_df, x="Stock", y="Return%")
plt.title("FAANG Monthly Return(March 2026)")
plt.xlabel("Stock")
plt.ylabel("Return%")
plt.show()

#c)
volume_pivot = df.pivot_table(
    index="ticker",
    columns="date",
    values="volume",
    aggfunc="mean"
)
plt.figure(figsize=(12,6))
sns.heatmap(volume_pivot)
plt.title("Daily Trading Volume Heatmap")
plt.xlabel("Date")
plt.ylabel("Stock")
plt.show()

In [6]:
#Task 4

#a)
import os
os.makedirs("exports", exist_ok=True)
df.to_json("exports/stockdata.json", orient="records", indent=4)

#b)
df.to_csv("exports/stockdata.csv", index=False)

#c)
df_json=pd.read_json("exports/stockdata.json")
display(df_json.head())

df_csv = pd.read_csv("exports/stockdata.csv")
display(df_csv.head())

,open,high,low,close,volume,adj_high,adj_low,adj_close,adj_open,adj_volume,split_factor,dividend,symbol,exchange,date,ticker
0,549.98,573.69,546.77,572.13,32809500,573.6900,546.77,572.13,549.98,32898272,1,0.0,META,ARCX,2026-03-31,META
1,536.38,539.55,528.54,536.38,22758800,539.5500,528.54,536.38,536.38,22795203,1,0.0,META,ARCX,2026-03-30,META
2,540.10,543.60,520.26,525.72,29980300,543.5999,520.26,525.72,540.10,30133010,1,0.0,META,ARCX,2026-03-27,META
3,582.49,583.00,543.35,547.54,35664700,583.0000,543.35,547.54,582.49,35780131,1,0.0,META,ARCX,2026-03-26,META
4,598.74,603.62,593.40,594.89,12161179,603.6700,593.40,594.89,598.74,12585031,1,0.0,META,ARCX,2026-03-25,META

,open,high,low,close,volume,adj_high,adj_low,adj_close,adj_open,adj_volume,split_factor,dividend,symbol,exchange,date,ticker
0,549.98,573.69,546.77,572.13,32809500.0,573.6900,546.77,572.13,549.98,32898272.0,1.0,0.0,META,ARCX,2026-03-31 00:00:00+00:00,META
1,536.38,539.55,528.54,536.38,22758800.0,539.5500,528.54,536.38,536.38,22795203.0,1.0,0.0,META,ARCX,2026-03-30 00:00:00+00:00,META
2,540.10,543.60,520.26,525.72,29980300.0,543.5999,520.26,525.72,540.10,30133010.0,1.0,0.0,META,ARCX,2026-03-27 00:00:00+00:00,META
3,582.49,583.00,543.35,547.54,35664700.0,583.0000,543.35,547.54,582.49,35780131.0,1.0,0.0,META,ARCX,2026-03-26 00:00:00+00:00,META
4,598.74,603.62,593.40,594.89,12161179.0,603.6700,593.40,594.89,598.74,12585031.0,1.0,0.0,META,ARCX,2026-03-25 00:00:00+00:00,META

In [7]:
#Task 5

#a)
import sqlite3
import pandas as pd
conn = sqlite3.connect("/storage/emulated/0/Download/northwind.db")

#b)
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [8]:
#c)
query = """
SELECT 
    c.CompanyName,
    COUNT(o.OrderID) AS total_orders
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
GROUP BY c.CompanyName
ORDER BY total_orders DESC
"""

df = pd.read_sql_query(query, conn)

print(df.head())

           CompanyName  total_orders
0                   IT           335
1        B's Beverages           210
2   Ricardo Adocicados           203
3    LILA-Supermercado           203
4  Gourmet Lanchonetes           202

In [9]:
#Task 6

#a)
top10 = df.head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    data=top10,
    x="total_orders",
    y="CompanyName"
)

plt.title("Number of Orders per Customer")
plt.xlabel("Number of Orders")
plt.ylabel("Customer")

plt.show()

#b)
df_orders = pd.read_sql_query(query, conn)
df_orders.head()

           CompanyName  total_orders
0                   IT           335
1        B's Beverages           210
2   Ricardo Adocicados           203
3    LILA-Supermercado           203
4  Gourmet Lanchonetes           202

In [10]:
#c)

conn = sqlite3.connect("/storage/emulated/0/Download/northwind.db")
query = """
SELECT 
    p.ProductName,
    SUM(od.Quantity * od.UnitPrice) AS revenue
FROM "Order Details" od
JOIN Products p
ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY revenue DESC
"""

df_products = pd.read_sql_query(query, conn)
display(df_products.head())

top10 = df_products.head(10)
plt.figure(figsize=(12,6))
sns.barplot(
    data=top10,
    x="revenue",
    y="ProductName"
)

plt.title("Top 10 Products by Revenue")
plt.show()

               ProductName      revenue
0            Côte de Blaye  53274482.70
1  Thüringer Rostbratwurst  24630836.96
2          Mishi Kobe Niku  19424638.00
3   Sir Rodney's Marmalade  16654879.80
4         Carnarvon Tigers  12607487.50

In [11]:
#Task 7

#a)
import sqlite3
import pandas as pd
conn = sqlite3.connect("/storage/emulated/0/Download/northwind.db")
df_products = pd.read_sql_query("SELECT * FROM Products", conn)
df_categories = pd.read_sql_query("SELECT * FROM Categories", conn)

display(df_products.head())
display(df_categories.head())

,ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1

,CategoryID,CategoryName,Description,Picture
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an...",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
2,3,Confections,"Desserts, candies, and sweet breads",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
3,4,Dairy Products,Cheeses,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...

In [12]:
#b)
query = """
SELECT 
    p.ProductID,
    p.ProductName,
    p.UnitPrice,
    c.CategoryName
FROM Products p
JOIN Categories c
ON p.CategoryID = c.CategoryID
"""

df_pc = pd.read_sql_query(query, conn)

df_pc.head()

   ProductID                   ProductName  UnitPrice CategoryName
0          1                          Chai      18.00    Beverages
1          2                         Chang      19.00    Beverages
2          3                 Aniseed Syrup      10.00   Condiments
3          4  Chef Anton's Cajun Seasoning      22.00   Condiments
4          5        Chef Anton's Gumbo Mix      21.35   Condiments

In [13]:
#c)

df_category_count = df_pc.groupby("CategoryName").size().reset_index(name="product_count")
df_category_count = df_category_count.sort_values("product_count", ascending=False)

plt.figure(figsize=(10,6))

sns.barplot(
    data=df_category_count,
    x="product_count",
    y="CategoryName"
)

plt.title("Number of Products per Category")
plt.show()

In [14]:
import time
start = time.time()

#6c
query = """
SELECT 
    p.ProductName,
    SUM(od.Quantity * od.UnitPrice) AS revenue
FROM "Order Details" od
JOIN Products p
ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY revenue DESC
"""
df_products = pd.read_sql_query(query, conn)
end = time.time()
time_6c = end-start

#7c
start2 = time.time()
df_category_count = df_pc.groupby("CategoryName").size().reset_index(name="product_count")
end2 = time.time()
time_7c = end2 - start2

print("6(c) time:", time_6c)
print("7(c) time:", time_7c)

if time_6c > time_7c:
    print("6(c) is slower")
else:
    print("7(c) is slower")

6(c) time: 0.41520047187805176
7(c) time: 0.0012874603271484375
6(c) is slower

In [15]:
#Task 8
import pandas as pd

wide_data = pd.DataFrame({ "store": ["Helsinki", "Tampere", "Turku"], "Q1_sales": [12000, 8500, 9200], "Q2_sales": [13500, 9100, 9800], "Q3_sales": [11800, 8800, 10100], "Q4_sales": [15000, 10200, 11500] })
long_data = pd.DataFrame({ "month": ["Jan", "Jan", "Feb", "Feb", "Mar", "Mar"], "product": ["Laptop", "Phone", "Laptop", "Phone", "Laptop", "Phone"], "units_sold": [45, 120, 50, 110, 55, 130] })

#a)
print("Before (Wide):") 
display(wide_data)
long_from_wide = pd.melt(
    wide_data,
    id_vars="store",
    var_name="quarter",
    value_name="sales"
)
print("After (Long):")
display(long_from_wide)

Before (Wide):

      store  Q1_sales  Q2_sales  Q3_sales  Q4_sales
0  Helsinki     12000     13500     11800     15000
1   Tampere      8500      9100      8800     10200
2     Turku      9200      9800     10100     11500

After (Long):

       store   quarter  sales
0   Helsinki  Q1_sales  12000
1    Tampere  Q1_sales   8500
2      Turku  Q1_sales   9200
3   Helsinki  Q2_sales  13500
4    Tampere  Q2_sales   9100
5      Turku  Q2_sales   9800
6   Helsinki  Q3_sales  11800
7    Tampere  Q3_sales   8800
8      Turku  Q3_sales  10100
9   Helsinki  Q4_sales  15000
10   Tampere  Q4_sales  10200
11     Turku  Q4_sales  11500

In [16]:
#b)
print("Before (long):")
display(long_data)

wide_from_long = long_data.pivot(
    index="month",
    columns="product",
    values="units_sold"
)
print("After (Wide):")
display(wide_from_long)

Before (long):

  month product  units_sold
0   Jan  Laptop          45
1   Jan   Phone         120
2   Feb  Laptop          50
3   Feb   Phone         110
4   Mar  Laptop          55
5   Mar   Phone         130

After (Wide):

product  Laptop  Phone
month
Feb          50    110
Jan          45    120
Mar          55    130

In [17]:
#c)
wide_back = long_from_wide.pivot(
    index="store",
    columns="quarter",
    values="sales"
).reset_index()
print("Wide restored:") 
display(wide_back)

long_back = wide_from_long.reset_index().melt(
    id_vars="month",
    var_name="product",
    value_name="units_sold"
)
print("Long restored:")
display(long_back)

Wide restored:

quarter     store  Q1_sales  Q2_sales  Q3_sales  Q4_sales
0        Helsinki     12000     13500     11800     15000
1         Tampere      8500      9100      8800     10200
2           Turku      9200      9800     10100     11500

Long restored:

  month product  units_sold
0   Feb  Laptop          50
1   Jan  Laptop          45
2   Mar  Laptop          55
3   Feb   Phone         110
4   Jan   Phone         120
5   Mar   Phone         130